### ISSUE TITLE
Mongoid::Errors::DocumentNotFound

### ISSUE THREAD

**Issue by rick-liu** [codingstyle-cn/codingstyle.cn#12]
Mongoid::Errors::DocumentNotFound (
message:
  Document not found for class User with attributes {:slug=>"products"}.
summary:
  When calling User.find_by with a hash of attributes, all attributes provided must match a document in the database or this error will be raised.
resolution:
  Search for attributes that are in the database or set the Mongoid.raise_not_found_error configuration option to false, which will cause a nil to be returned instead of raising this error.):
  app/models/user.rb:250:in `find_login'
  app/controllers/users_controller.rb:123:in`find_user'

**Comment by rckv** [comment]
Mongoid::Errors::DocumentNotFound (
message:
  Document(s) not found for class Topic with id(s) 6.
summary:
  When calling Topic.find with an id or array of ids, each parameter must match a document in the database or this
 error will be raised. The search was for the id(s): 6 ... (1 total) and the following ids were not found: 6.
resolution:
  Search for an id that is in the database or set the Mongoid.raise_not_found_error configuration option to false,
 which will cause a nil to be returned instead of raising this error when searching for a single id, or only the m
atched documents when searching for multiples.):
  app/controllers/topics_controller.rb:75:in `show'

**Comment by rckv** [comment]
Mongoid::Errors::DocumentNotFound (
message:
  Document(s) not found for class Node with id(s) 8.
summary:
  When calling Node.find with an id or array of ids, each parameter must match a document in the database or this 
error will be raised. The search was for the id(s): 8 ... (1 total) and the following ids were not found: 8.
resolution:
  Search for an id that is in the database or set the Mongoid.raise_not_found_error configuration option to false,
 which will cause a nil to be returned instead of raising this error when searching for a single id, or only the m
atched documents when searching for multiples.):
  app/controllers/topics_controller.rb:34:in `node'
